### ISSUE TITLE
Couple of questions

### ISSUE THREAD

**Issue by wihodges** [nystudio107/craft-webperf#1]
Watched your youtube livestream preview, super excited about this plugin!

Couple of non-live questions:

1) Have you considered using a median value instead of mean with 10x outlier filter? Perhaps even a quartile type bar chart for aggregate data, would be interesting. Averages can be a bit misleading depending on who you ask.

2) Would there be anyway to filter by traffic source. Example being a glicd or utm parameter. I've noticed on many of the sites I work on that have heavy paid media [gclid] traffic, performance and errors are pretty wild almost all outliers of typical user. So it would be nice to compare traffic of organic users vs paid media. 

3) In addition to browser & os, is there potential to capture internet connection through https://developer.mozilla.org/en-US/docs/Web/API/Network_Information_API – although seems pretty limited browser support.

4) A super nice to have, would there be a way to send the session data recorded to webhook or javascript source such as GA event, Segment or Matamo? I say that just out of experience, that most of the reporting/monitoring happens outside of craft so rolling it up into an common dashboard would be helpful - although I think the dashboards you've created already top most of the monitoring tools I've used.

Great work.

**Comment by khalwat** [comment]
> 1) Have you considered using a median value instead of mean with 10x outlier filter? Perhaps even a quartile type bar chart for aggregate data, would be interesting. Averages can be a bit misleading depending on who you ask.

So the primary reason I'm using mean is simply that it's fast; there's a built-in SQL function to calculate an average, whereas calculating a median is more intensive. This auto-trimming is done at request time normally (though you can turn this off and run it via CLI if you like), so performance is a consideration.

I'm open to ideas on ways to make it better after 1.0 is released though!

> 2) Would there be anyway to filter by traffic source. Example being a glicd or utm parameter. I've noticed on many of the sites I work on that have heavy paid media [gclid] traffic, performance and errors are pretty wild almost all outliers of typical user. So it would be nice to compare traffic of organic users vs paid media. 

Currently no, but I like the idea of giving advanced users an array of RegEx's that they can throw at the incoming requests to filter things out.

It does record the query string which would include any of the various UTM parameters, though.

> 3) In addition to browser & os, is there potential to capture internet connection through https://developer.mozilla.org/en-US/docs/Web/API/Network_Information_API – although seems pretty limited browser support.

So I did look into this, but the primary reason I didn't include bandwidth testing is it complicates the request; by necessity, the bandwidth test has to occur during the request. I feel it needs careful consideration and testing before adopting it. But I may just be overly paranoid.

> 4) A super nice to have, would there be a way to send the session data recorded to webhook or javascript source such as GA event, Segment or Matamo? I say that just out of experience, that most of the reporting/monitoring happens outside of craft so rolling it up into an common dashboard would be helpful - although I think the dashboards you've created already top most of the monitoring tools I've used.

So yes actually -- I built in events that fire both before & after Data Samples are recorded, and Error Samples are recorded. That means any plugin/module can listen to the data and do whatever it wants (including telling it not to record the data / error sample). It also means the Webhooks plugin can be used to do whatever you want.

Thanks for your interest in the plugin!
