### ISSUE TITLE
Occasional exception: Undefined property: WhichBrowser\Model\Browser::$name

### ISSUE THREAD

**Issue by Coysh** [nystudio107/craft-webperf#10]
I track errors using BugSnag, and has reported about 20 instances of the following:

`yii\base\ErrorExceptionPOST /webperf/metrics/beacon
Undefined property: WhichBrowser\Model\Browser::$name
.../vendor/nystudio107/craft-webperf/src/controllers/MetricsController.php:166`

**Comment by khalwat** [comment]
Very useful, thanks, I will have a look.

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-webperf/commit/b7c1fe4e394a38185a0582306f01a9f8f17f5004
