### ISSUE TITLE
Setting to disable Samples from Live Preview?

### ISSUE THREAD

**Issue by jmcgaha** [nystudio107/craft-webperf#14]
I recently added this to a site with some performance issues and my client noticed that if you are using Live Preview, it's recording a new sample every time it refreshes live preview which potentially results in a lot of samples and could perhaps end up skewing the data.

I just wonder if it would make sense to have a config option to turn off recording data in Live Preview.

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-webperf/commit/0af65620dead979d819b055ebd7067208af7c6f3
