### ISSUE TITLE
Server Performance not collecting samples

### ISSUE THREAD

**Issue by louderthan10** [nystudio107/craft-webperf#15]
Hi Andrew,

Any reason you can think of as to why the Server Performance section wouldn't be collecting samples? I've got over 40k in both Browser and Craft performance, but nada under Server Performance:

<img width="1057" alt="Screen Shot 2019-04-23 at 10 40 55" src="https://user-images.githubusercontent.com/49751/56603778-3e497c00-65b5-11e9-9106-f76461deb742.png">

I'm running:

* Craft 3.1.23
* Webperf 1.0.7
* PHP 7.2.17
* MySQL 5.7.25 (running on its own remote server)
* Also included a WebPageTest API key

Ideas? Maybe a server config thing I need to turn on/adjust?

**Comment by louderthan10** [comment]
Quick update, I now have 1 sample under the Server Performance section… so I guess it's doing something.

**Comment by khalwat** [comment]
What type of caching are you using for the server @louderthan10 ?

**Comment by khalwat** [comment]
Also what do your plugin settings look like? You have the **Include Browser Beacon** and **Include Craft Beacon** turned on yes?

It definitely should be sampling more often, assuming it's actually hitting Craft for the requests for your site.

Based on what I'm seeing here, something really doesn't seem right. Can you hit me up on Discord or via Twitter so we can do a screen sharing?

**Comment by khalwat** [comment]
I looked at your site real quick, and I think it's due to ModPagespeed doing weird stuff to your page ->

https://developers.google.com/speed/pagespeed/module/

The HTML doesn't appear to be valid; WC3 validator seems to agree with that:

https://validator.w3.org/nu/?doc=https%3A%2F%2Flouderthanten.com%2F

**Comment by cole007** [comment]
Know this is closed but in case anyone else stumbles upon this issue we had similar and identified the case as being Snaptcha.

Adding the two following webperf controller actions into the `Exclude Controller Actions` config for Snaptcha has fixed the problem:

- `webperf/metrics/beacon`
- `webperf/render/amp-iframe`
