### ISSUE TITLE
Consider adding DB index

### ISSUE THREAD

**Issue by ostark** [nystudio107/craft-webperf#19]
I noticed this query on a larger dataset (300K rows):

```
SELECT *
FROM `webperf_data_samples`
WHERE `requestId`=99999999999999
LIMIT 1
```

An index on `webperf_data_samples.requestId` might be useful :-)

**Comment by khalwat** [comment]
This is likely the query that does the db trimming. There are controls for when and how this query happens (and a CLI tool that can be used to run it via cron as needed).

But I agree, I'll add an index.

**Comment by khalwat** [comment]
Addressed in https://github.com/nystudio107/craft-webperf/commit/ecdec4bcbe9f65446f82d7e15f4b32be469dffc0
