### ISSUE TITLE
Webperf is displaying 0 samples

### ISSUE THREAD

**Issue by khalwat** [nystudio107/craft-webperf#22]
Webperf displays that there are 0 data samples because the _average_ of the number of samples for all of the pages is < 1

Probably it should round up or display something more useful

![unknown](https://user-images.githubusercontent.com/7570798/70470505-27e72680-1a99-11ea-9258-21800d53a882.png)

**Comment by khalwat** [comment]
Ended up being an updated date picker that broke the shortcuts format, of all things. Yay, semver?

Fixed in https://github.com/nystudio107/craft-webperf/commit/8d5da25b1bee7bc7a2a972e3e5008bdc5e5774bd

**Comment by darylknight** [comment]
Thanks Andrew! Only thing I was going to add is that it's when the average is less than <100, not <1. Although you've found the cause now.
