### ISSUE TITLE
TypeError in Craft 3.7.2

### ISSUE THREAD

**Issue by E2design** [nystudio107/craft-webperf#38]
### Describe the bug
The bug shows when I open up a category entry

### To reproduce
Steps to reproduce the behaviour:
1. Go to "CP main left menu"
2. Click on "Categories and double click a category"
3. See error message "Argument 1 passed to nystudio107\webperf\Webperf::renderSidebar() must be an instance of craft\base\Element, null given, called in /var/www/project/cms/vendor/nystudio107/craft-webperf/src/Webperf.php on line 586"

### Screenshots
See [this](https://cln.sh/dplyd1) link

### Versions
- Plugin version: 1.0.24
- Craft version: 3.7.2

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-webperf/commit/daf48b8e0b814c66a24353a12f6eeeda21a7734f

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-webperf": "dev-develop as 1.0.25”,
```
Then do a `composer clear-cache && composer update`
