### ISSUE TITLE
Sidebar not rendering

### ISSUE THREAD

**Issue by Coysh** [nystudio107/craft-webperf#40]
### Describe the bug
On all elements - the Sidebar is not rendering and is throwing an error.

```
Error rendering `_sidebars/webperf-sidebar.twig` -> An exception has been thrown during the rendering of a template ("The file or directory to be published does not exist: /home/eauk/www.eauk.org/vendor/nystudio107/craft-webperf/src/assetbundles/webperf/dist").
```

### To reproduce
Steps to reproduce the behaviour:
1. Go to any entry
2. See error message

### Expected behaviour
See WebPerf sidebar

### Screenshots
<img width="563" alt="CleanShot 2022-02-10 at 12 14 19@2x" src="https://user-images.githubusercontent.com/5764356/153406752-3fce3a5d-2140-409c-ae53-b9b450668f50.png">

### Versions
- Plugin version: 1.0.26
- Craft version:  3.7.28

**Comment by khalwat** [comment]
This was fixed in 1.0.27 -- please update to the latest version. 

https://github.com/nystudio107/craft-webperf/releases/tag/1.0.27
