### ISSUE TITLE
Sidebar UI has been a bit of a mess for a while

### ISSUE THREAD

**Issue by corneliusio** [nystudio107/craft-webperf#51]
### Describe the bug

<img width="362" alt="Screenshot 2024-01-30 at 4 10 03 PM" src="https://github.com/nystudio107/craft-webperf/assets/4140885/521c123f-bd7e-4baa-8a18-2db0e181c54b">

I'm assuming I don't need to breakdown how to reproduce and what is expected.

### Versions
- Plugin version: 4.0.0
- Craft version: Craft Pro 4.5.10

Also is the same for Chrome, Firefox, and Safari.

**Comment by khalwat** [comment]
I'm assuming you mean the cropping of the "Page loaded" graph, and the lack of padding around the rest of it?

Anything I missed?

**Comment by corneliusio** [comment]
Yes, sorry. Rereading my post realized it probably came across pretty short. Was working very quickly that day and just wanted to submit the issue real quick. 

Only things I've notice are the SVG clipping and the text padding.

**Comment by khalwat** [comment]
<img width="366" alt="Screenshot 2024-02-03 at 12 03 37 PM" src="https://github.com/nystudio107/craft-webperf/assets/7570798/7e727206-f6bf-43b3-a432-46f42ed3f885">

There, that's a bit better.

Addressed in: 

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-webperf": "dev-develop as 1.0.29”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 4:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-webperf": "dev-develop-v4 as 4.0.1”,
```
Then do a `composer clear-cache && composer update`
