### ISSUE TITLE
Metrics Widget

### ISSUE THREAD

**Issue by baileydoestech** [nystudio107/craft-webperf#6]
It looks like the metrics widget might not be quite finished ?

![image](https://user-images.githubusercontent.com/3185073/52940970-b1d5cf80-335f-11e9-875a-d2649520ebf7.png)

**Comment by baileydoestech** [comment]
If any does use the widget (as I accidentally did) you will not be able to get into the admin dashboard until the row is deleted from craft_widgets table in the DB.

**Comment by khalwat** [comment]
Ahhhhhh, I forgot to remove it, thank you :)

**Comment by khalwat** [comment]
I ultimately decided that Webperf itself was a dashboard, and so having a Widget was largely useless.

**Comment by khalwat** [comment]
Addressed in https://github.com/nystudio107/craft-webperf/commit/26466a74ffb83ec221ce23088d1463dec8feaa8d
