### ISSUE TITLE
Turn off/hide settings when 'allowAdminChanges' is set to false

### ISSUE THREAD

**Issue by wbrowar** [nystudio107/craft-webperf#9]
When `allowAdminChanges` is set to `false`, changing plugin settings results in a "Internal Server Error".

**Comment by khalwat** [comment]
hmmmm. Can you get me a stack trace?

If this is an issue with Webperf, it's probably an issue with SEOmatic and Retour as well.

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-webperf/commit/475dae3994daefec0d2ca9781c1d04e0a6157afc

**Comment by khalwat** [comment]
And yes, it's an issue in SEOmatic and Retour as well.
